apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myweb-deploy
  name: myweb-deploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myweb-deploy
status:
  loadBalancer: {}
